input("Give me a word! ")
print()
input("Give me a second word! ")
print()
input("Great, now your favourite number! ")
print()
input("And your second-favourite number... ")
print()
print("Whew! Wasn't that fun?")
