print("+---------------------------------------------------------+")
print("|                                                         |")
print("|                                                         |")
print("|                                                         |")
print("|                                                         |")
print("|                    Mr. Servidio                         |")
print("|                    St. Robert CHS                       |")
print("|                    8101 Leslie St                       |")
print("|                    Thornhill, ON                        |")
print("|                    L3T 7P4                              |")
print("|                                                         |")
print("+---------------------------------------------------------+")
