name = input("Hello. What is your name? ")
print()
age = input(f"Hi, {name}! How old are you? ")
print()
print(f"So you're {age}, eh?  That's not old at all!")
print()
salary = input("How much do you make, Dennis? ")
print()
print(f"{salary}! I hope that's per hour and not per year! LOL!")
